#!/usr/bin/env python3
"""gap_table.py -- per-n companion table for the four-square balance gap.

For every n it prints the most balanced four-square decomposition and the
running gap record, so a reader can see -- without computing anything by hand --
each number's tightest representation and why a gap-record location is a record
versus the ordinary numbers around it.

    python3 gap_table.py            > table.csv   # n = 1..20000 (default)
    python3 gap_table.py 100000     > table.csv   # n = 1..100000

Columns (one row per n; every n is a sum of four squares -- Lagrange):

    n             the integer
    x,y,z,w       the most balanced decomposition, x >= y >= z >= w >= 0,
                  x^2 + y^2 + z^2 + w^2 = n (minimal largest part x)
    gap           x - ceil(sqrt(n/4)) = g(n), the balance gap (the headline
                  statistic); 0 means x is as small as arithmetic allows
    best_so_far   the largest gap seen at any m <= n (running maximum)
    is_record     1 where gap exceeds every smaller n, else 0
    record_index  1, 2, 3, ... counting the gap records; blank on non-records
    spread        x - w, how far the largest and smallest parts sit apart
                  (shown for context only; not a record column)

Every row is self-checking: x*x + y*y + z*z + w*w = n and gap = x - ceil(sqrt(n/4)).
The engine is the exact 'min' mode of src/foursquare.py (the ground-truth
checker); for scale use the C engine. Filtering is_record = 1 reproduces the
prefix of the gap-record-location sequence.
"""
import os
import sys
import math

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from foursquare import canonical

HEADER = """\
# Four-square balance gap -- per-n companion table.
# Every n = x^2 + y^2 + z^2 + w^2 with x >= y >= z >= w >= 0 (Lagrange).
# (x,y,z,w) is the most balanced such decomposition (minimal largest part x).
# gap = x - ceil(sqrt(n/4)) = g(n); spread = x - w (context only).
#   Check any row by hand: x*x + y*y + z*z + w*w = n and gap = x - ceil(sqrt(n/4)).
# is_record = 1 where gap exceeds every smaller n (running maximum);
#   best_so_far is that running maximum; record_index counts the records 1,2,3,...
# Illustrative companion to the gap-record-location sequence; generated by
#   src/gap_table.py (engine src/foursquare.py, 'min' mode)."""

COLUMNS = "n,x,y,z,w,gap,best_so_far,is_record,record_index,spread"


def xmin(n: int) -> int:
    """ceil(sqrt(n/4)): the smallest largest-part any decomposition could have."""
    x = math.isqrt((n + 3) // 4)
    while 4 * x * x < n:
        x += 1
    return x


def rows(N: int):
    best = -1
    rank = 0
    for n in range(1, N + 1):
        x, y, z, w = canonical(n, "min")
        g = x - xmin(n)
        rec = 1 if g > best else 0
        if rec:
            best = g
            rank += 1
        yield (n, x, y, z, w, g, best, rec, rank if rec else "", x - w)


def main(argv):
    N = int(argv[1]) if len(argv) > 1 else 20000
    out = sys.stdout
    out.write(HEADER + "\n")
    out.write(COLUMNS + "\n")
    for r in rows(N):
        out.write(",".join(str(v) for v in r) + "\n")


if __name__ == "__main__":
    main(sys.argv)
